Session2 天気予報を取得し、表示する
yumemi-rnose/yumemi-flutter-training pull request #15
Opened 2024-07-10 02:06 UTC by yumemi-rnose

## 課題
Session2 天気予報を取得し、表示する
close #3 

## 対応箇所

- [x] 天気予報を取得する
- [x] Reload ボタンをタップして取得した天気予報を画面に表示する

### [レビュー項目](https://yumemi.notion.site/Flutter-555155c98aea49f2bc745bbaff9d6ec7)
- [x] pubspec.yaml に画像を追加する際、ディレクトリで指定しているか
- [x] YumemiWeather() を build 関数内でインスタンス化していないか
- [x] API の使用箇所でエラーハンドリングしているか
- [x] 天気の種類をenumで扱っているか
- [x] Enum の .values.byName() を使用していないか
- [x] テストのことを考えて、YumemiWeather のインスタンスを DI しているか
- [x] アセットの指定間違い防止を考慮できているか

## 動作

| iOS | android |
|----------|--------|
| <div><video controls src="https://github.com/yumemi-rnose/yumemi-flutter-training/assets/47808571/89707b06-fd37-4f10-bca5-d5c6824319c1" muted="false"></video></div> | <div><video controls src="https://github.com/yumemi-rnose/yumemi-flutter-training/assets/47808571/3765eb9b-3bab-4c64-9da2-54abf4fe2f5e" muted="false"></video></div> |

2024-07-10 02:15 UTC, nerd0geek1 commented on lib/weather_model.dart
> +  non,
@yumemi-rnose 
`non`ではなく、`none`が正しいのではないでしょうか？

2024-07-10 02:22 UTC, nerd0geek1 commented on lib/weather_model.dart
> +      return WeatherType.values.byName(response);
@yumemi-rnose 
`Enum.values.byName`は想定外の値が来た際に、`ArgumentError`をthrowしてしまうため、適切ではないですね。

このあたりをご参照ください。
https://api.flutter.dev/flutter/dart-core/EnumByName/byName.html
https://zenn.dev/iwaku/articles/2020-12-19-iwaku

2024-07-10 02:23 UTC, nerd0geek1 requested changes
@yumemi-rnose 
一通り確認して、気になるところにコメントしました。

2024-07-10 03:08 UTC, yumemi-rnose commented on lib/weather_model.dart
> +  non,
@nerd0geek1 
[c1f2c5e](https://github.com/yumemi-rnose/yumemi-flutter-training/pull/15/commits/c1f2c5e17fde544984967b4597677964a7de6eae) にて修正しました。

2024-07-10 03:10 UTC, yumemi-rnose commented on lib/weather_model.dart
> +      return WeatherType.values.byName(response);
@nerd0geek1 
レビューありがとうございます。
[e34e609](https://github.com/yumemi-rnose/yumemi-flutter-training/pull/15/commits/e34e6091295c693d838081cdbf337ff89dda593d) にて修正しました。
`ArgmuentError` って `on Exception catch (e) {` で catchしてくれないんですね。

2024-07-10 03:11 UTC, yumemi-rnose commented
@nerd0geek1 
再度レビューお願いいたします。

2024-07-10 03:14 UTC, nerd0geek1 commented on lib/weather_model.dart
> +      return WeatherType.values.byName(response);
@yumemi-rnose 
上記のzennの記事に記載があるよう、

- Exception
  - 実行時エラー
- Error
  - そもそも、プログラム的によろしくない(よって修正の必要あり)

という形ですので。

2024-07-10 03:15 UTC, nerd0geek1 commented on lib/weather_screen.dart
> +  }
@yumemi-rnose 
このあたりはなくても良いかもですが、意図をもって追加されていますでしょうか？

2024-07-10 03:19 UTC, yumemi-rnose commented on lib/weather_screen.dart
> +  }
@nerd0geek1 
この[Check](https://github.com/yumemi-rnose/yumemi-flutter-training/actions/runs/9867010514)のActionsでエラーになってしまったので追加しました

2024-07-16 01:23 UTC, nerd0geek1 commented on lib/weather_screen.dart
> +  }
@yumemi-rnose 
こういう話もされているようなので、このlint自体、無効化しても良いかもです！
https://yumemi.slack.com/archives/C0585H2BG9L/p1720493664019749

2024-07-16 01:38 UTC, yumemi-rnose commented on lib/weather_screen.dart
> +  }
@nerd0geek1 

> @yumemi-rnose こういう話もされているようなので、このlint自体、無効化しても良いかもです！ https://yumemi.slack.com/archives/C0585H2BG9L/p1720493664019749

なるほど。こちらのやり方で `debugFillProperties` を消せました。ありがとうございます。
[9fb321e](https://github.com/yumemi-rnose/yumemi-flutter-training/pull/15/commits/9fb321e284a49741adcce606f01c82a57ca8c14f)
再度確認お願いします。

2024-07-16 01:46 UTC, nerd0geek1 approved these changes
![LGTM](https://i.lgtm.fun/2sud.gif)

2024-07-16 01:59 UTC, yumemi-rnose commented
レビューありがとうございます。
マージします

2024-07-16 01:59 UTC, merged