Session3 StatefulWidget のライフサイクル
yumemi-rnose/yumemi-flutter-training pull request #16
Opened 2024-07-12 05:31 UTC by yumemi-rnose

## 課題
StatefulWidget のライフサイクル
close #4

## 対応箇所

- [x] 緑色の画面を作成
- [x] 起動画面を前回まで作っていた画面から緑色画面に変更
- [x] 緑色の画面が表示されたら、0.5 秒後に前回まで作っていた画面に遷移する
- [x] 前回まで作っていた画面の Close ボタンをタップすると画面を閉じる

## レビューポイント

- [x] build メソッド直下で画面遷移処理を書いていないか
- [x] sleep を使っていないか
- [x] mounted のチェックをしているか
- [x] 初期画面と天気画面の Widget を分割しているか
- [x] iOS・Android のスワイプバックを考慮しているか

## 動作

| iOS |
|----------|
| <video src="https://github.com/user-attachments/assets/d3dc0fea-3a42-4a4b-8b00-a0be5a9984f7"> |

| android |  |
|:-:|:-:|
| スワイプバック | <img width="320" alt="ファイル名" src="https://github.com/user-attachments/assets/91b8b3c8-36db-46ef-baa4-eccbf852d450"> |
| クローズボタン | <img width="320" alt="ファイル名" src="https://github.com/user-attachments/assets/5b3db27b-1a6b-4402-a9e6-fc0615d2f4cf"> |

2024-07-16 01:57 UTC, nerd0geek1 commented on lib/green_back_screen.dart
> +      body: Container(color: Colors.green,),
@yumemi-rnose 
dartコードについてのフィードバックではないのですが、`.vscode/settings.json`を更新して、
`editor.formatOnSave`を追加したほうが良いかもです！(コードを保存するたびにコードフォーマットが実行される)

2024-07-16 02:04 UTC, yumemi-rnose commented on lib/green_back_screen.dart
> +      body: Container(color: Colors.green,),
@nerd0geek1 
[ad83715](https://github.com/yumemi-rnose/yumemi-flutter-training/pull/16/commits/ad8371591eaba8428161646a6002e3af02407472) にて追加しました。

2024-07-16 02:23 UTC, nerd0geek1 commented on lib/green_back_screen.dart
> +      if (mounted) {
@yumemi-rnose 
こちらですが、`Future.delayed`の第2引数内でチェックすべきではないでしょうか？
(`const Duration(milliseconds: 500) `の間にunmountされることがあるため)

2024-07-16 02:24 UTC, nerd0geek1 commented on lib/green_back_screen.dart
> +            ),
@yumemi-rnose 
この書き方では、一度しか発火しないのではないでしょうか？

2024-07-16 03:26 UTC, yumemi-rnose commented on lib/green_back_screen.dart
> +      if (mounted) {
@nerd0geek1 
レビューありがとうございます。
[3137072](https://github.com/yumemi-rnose/yumemi-flutter-training/pull/16/commits/31370725943968421be35fce4de8fa87c5e9dd39) にて修正しましたので再度ご確認お願いします。

2024-07-16 03:27 UTC, yumemi-rnose commented on lib/green_back_screen.dart
> +            ),
@nerd0geek1 
レビューありがとうございます。
[446f323](https://github.com/yumemi-rnose/yumemi-flutter-training/pull/16/commits/446f323d09ca6ea3264c5837d49c0562e5baa50f) にて修正しましたので再度ご確認お願いします。

2024-07-16 04:49 UTC, nerd0geek1 commented on lib/green_back_screen.dart
> +                navigate();
@yumemi-rnose 
挙動的には良いのですが、`async/await`を用いて記述するのがDartでは一般的ですね。

2024-07-16 04:49 UTC, nerd0geek1 requested changes
@yumemi-rnose 
コメントしました！

2024-07-16 06:15 UTC, yumemi-rnose commented on lib/green_back_screen.dart
> +                navigate();
@nerd0geek1 
[97feee0](https://github.com/yumemi-rnose/yumemi-flutter-training/pull/16/commits/97feee0d89b88e06c33499428e9165e07982245a) 修正してみました。
認識あってます？

2024-07-16 07:08 UTC, nerd0geek1 commented on lib/green_back_screen.dart
> +                navigate();
@yumemi-rnose 
`navigate`を複数回呼ぶと意図しない挙動になるのではないですかね？
`navigate`と`_navigate`に含まれるコードは正しいのですが、まとめ方が意図した通りではないですね。。

2024-07-16 09:13 UTC, yumemi-rnose commented on lib/green_back_screen.dart
> +                navigate();
@nerd0geek1 
こんな感じでどうでしょう？？
[a9d7ea5](https://github.com/yumemi-rnose/yumemi-flutter-training/pull/16/commits/a9d7ea54e9c7f5f3afb31a3e890b724ae337fa23) 再度お願いします。

2024-07-17 01:34 UTC, nerd0geek1 commented on lib/green_back_screen.dart
> +                navigate();
@yumemi-rnose 
あー、説明します。

今回の課題のまとまりとしては
- `WidgetBinding.instance.endOfFrame`で画面レイアウトが終わったタイミングで画面遷移をトリガーすること
- 0.5秒のdelayを入れて、画面遷移を行う。画面遷移から戻り次第、同じ処理をトリガーする

であるべき、と考えています。

97feee0 は概ね良かったのですが、画面遷移から戻ったタイミングで、`WidgetBinding.instance.endOfFrame`を含む処理を呼んでしまっており、その点を修正する必要があるように考えた(別の画面から戻ってきたタイミングでレイアウトは再実行されないため、`endOfFrame`を呼ぶ必要がない)、というわけです。

2024-07-17 01:50 UTC, yumemi-rnose commented on lib/green_back_screen.dart
> +                navigate();
@nerd0geek1 
説明ありがとうございます。
[d23f896](https://github.com/yumemi-rnose/yumemi-flutter-training/pull/16/commits/d23f89691a29ada0c9f891b948df7222dd16f562) にて修正しました。

2024-07-17 01:51 UTC, nerd0geek1 commented on lib/green_back_screen.dart
>      await WidgetsBinding.instance.endOfFrame;
[nits]
ちなみに、`WidgetsBinding.instance`系の処理は慣習的にthenで問題なかったりします。

2024-07-17 01:51 UTC, nerd0geek1 approved these changes
![LGTM](https://i.lgtm.fun/2swm.png)

2024-07-17 01:58 UTC, yumemi-rnose commented on lib/green_back_screen.dart
>      await WidgetsBinding.instance.endOfFrame;
@nerd0geek1 
修正しました。ありがとうございます。
[c78f62c](https://github.com/yumemi-rnose/yumemi-flutter-training/pull/16/commits/c78f62c112b5f74d0cb6d41cd0656ee5d5d1243d)

2024-07-17 01:58 UTC, nerd0geek1 approved these changes

2024-07-17 01:59 UTC, merged